### ISSUE TITLE
`PopulateRepository` in Server Run method

### ISSUE THREAD

**Issue by AlxndrJhn** [seashell/drago#17]
https://github.com/seashell/drago/blob/b9584f631a8bcd27618500f84ae7579bf2c1eb07/agent/server/server.go#L30
I did not start the server locally to check if the `/links` or `/hosts` endpoint returns the dummies but it seems like this line should be deleted.
It gets called here https://github.com/seashell/drago/blob/983a2e9c4bf21ffbb93d632b983bc312ff2ae25f/agent/agent.go#L54

I assume the "dummies" it creates are for testing purposes only?

**Comment by edufschmidt** [comment]
Thanks! This was intended for adding mock data to the repository, but since it's no longer used, we removed it in the latest PR.
