### ISSUE TITLE
Alliance

### ISSUE THREAD

**Issue by Ponchale1** [seashell/drago#41]
Hello, my name is Alfonso Hernandez. I work for the Astian Foundation, a non-profit organization that offers free software and technologies.

We are the organization responsible for development and maintenance of Midori Browser, a popular browser, light, fast, secure and open source.

We are developing a service called K-LamarVPN using WireGuard, which we hope to link with Midori. We would like to establish an alliance with the project to implement it.

What do you think?

**Comment by edufschmidt** [comment]
Hello Alfonso, thanks for your message.

Sounds interesting. Maybe we could schedule a call next week to discuss what you have in mind. 

Would you mind sending me an email at eschmidt@seashell.sh with dates/times you have available?

Cheers!

**Comment by Ponchale1** [comment]
ready
