### ISSUE TITLE
Dockerfile or pre-compiled docker images support

### ISSUE THREAD

**Issue by xczh** [seashell/drago#44]
Thank you for your efforts on this project. It looks like a great idea! Could you provide a `Dockerfile` for compiling the whole project? Or are there any provide a pre-compiled docker images? I just want to try a demo :)

**Comment by edufschmidt** [comment]
Hi @xczh. Thank you for your kind words, and sorry for the delay in replying. The Docker container for building the project will be available in a few days. If you have Go installed, you can easily run the client and the server by checking out the `dev` branch and running `go run main.go agent --dev`. If you have any other suggestions, feel free to share them :)

**Comment by edufschmidt** [comment]
A Dockerfile is now available for those interested in building Drago without having to install anything in their system. See  PR #46.
